Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCWebStore.Models;
using MVCWebStore.ViewModels;

namespace MVCWebStore.Controllers
{
    public class ShopController : Controller
    {
        private readonly IArtworkRepository _artworkRepository;

        public ShopController(IArtworkRepository artworkRepository)
        {
            _artworkRepository = artworkRepository;
        }

        public IActionResult Index()
        {
            ArtworkViewModel artworkViewModel = new ArtworkViewModel();
            artworkViewModel.AllArtwork = _artworkRepository.AllArtwork;
            artworkViewModel.ArtworkCount = _artworkRepository.AllArtwork.Count();

            return View(artworkViewModel);
        }

        public IActionResult Detail(int id)
        {
            var artwork = _artworkRepository.GetArtworkById(id);
            if (artwork == null)
            {
                return NotFound();
            }
            return View(artwork);
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCWebStore.Models;
using MVCWebStore.ViewModels;

namespace MVCWebStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IArtworkRepository _artworkRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IArtworkRepository artworkRepository, ShoppingCart shoppingCart)
        {
            _artworkRepository = artworkRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int artworkId)
        {
            var selectedArtwork = _artworkRepository.AllArtwork.FirstOrDefault(p => p.ArtworkId == artworkId);

            if (selectedArtwork != null)
            {
                _shoppingCart.AddToCart(selectedArtwork, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int artworkId)
        {
            var selectedArtwork = _artworkRepository.AllArtwork.FirstOrDefault(p => p.ArtworkId == artworkId);

            if (selectedArtwork != null)
            {
                _shoppingCart.RemoveFromCart(selectedArtwork);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shop/Detail.cshtml
@model Artwork

    <div class="container text-center">
            <img src="@Model.ImageUrl" class="w-100"  />
            <p class="lead">@Model.Name</p>
            <p class="lead">@Model.Price.ToString("c")</p>
            <a class="text-warning"
               asp-controller="ShoppingCart"
               asp-action="AddToShoppingCart"
               asp-route-artworkId="@Model.ArtworkId">Order Print</a>
            <hr />
            <a asp-controller="Shop" asp-action="Index">Back to Shop</a>
    </div>

Views/Shop/Index.cshtml
@model ArtworkViewModel

    <h5 class="text-center">Welcome to our web store!</h5>
    
    <p class="text-center">@Model.ArtworkCount prints in stock</p>

        <div class="row">
            
                @foreach (var artwork in Model.AllArtwork)
                { 
                    <partial name="_ArtworkCard" model="artwork" />
                }
        </div>
    
   
    